version: '3.8'
services:
  stats-server:
    build: statisticsService/service
    image: ewm_stats_server_dock_image
    container_name: ewm_statistics_service
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/exploreWithMeStat
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  stats-db:
    image: postgres:14-alpine
    container_name: stats_postrges_db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_DB=exploreWithMeStat
      - POSTGRES_PASSWORD=default

  ewm-service:
    build: ewmService
    image: ewm_service_dock_image
    container_name: ewm_service
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - SERVICE_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/exploreWithMe
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_postrges_db
    ports:
      - "6542:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_DB=exploreWithMe
      - POSTGRES_PASSWORD=default

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8083:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ewm@gmail.com
      PGADMIN_DEFAULT_PASSWORD: default
    depends_on:
      - stats-db
      - ewm-db
    links:
      - stats-db
      - ewm-db
