version: '3.8'
services:
  stats-server:
    build: statisticsService/service
    image: stats_server_dock_image
    container_name: statistics_service
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/exploreWithMeStat
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  stats-db:
    image: postgres:14-alpine
    container_name: stats_postrges_db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_DB=exploreWithMeStat
      - POSTGRES_PASSWORD=default

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ewm@gmail.com
      PGADMIN_DEFAULT_PASSWORD: default
    depends_on:
      - stats-db
    links:
      - stats-db
